backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"
local_backend: true

collections:
  - name: "work"
    label: "Works"
    folder: "src/content/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }